version: '3.9'

services:
  php:
    image: harbor.skni.edu.pl/library/filmweeb-back:latest
    container_name: filmweeb-php
    networks:
      - filmweeb
    restart: always

  nginx-back:
    image: harbor.skni.edu.pl/library/filmweeb-back-nginx:latest
    container_name: filmweeb-nginx-back
    networks:
      - filmweeb
    ports:
      - 20001:80
    depends_on:
      - php
    restart: always

networks:
  filmweeb:

