version: '3.9'

services:
  php:
    image: harbor.skni.edu.pl/library/filmweeb-back:latest
    container_name: filmweeb-php
    restart: always
    ports:
      - 9000

  nginx-back:
    image: harbor.skni.edu.pl/library/filmweeb-back-nginx:latest
    container_name: filmweeb-nginx-back
    ports:
      - 80
    depends_on:
      - php
    restart: always
