version: '3.9'

services:
  php:
    image: kni.prz.edu.pl:9443/library/filmweeb-back:latest
    container_name: filmweeb-php
    networks:
      - filmweeb

  db:
    image: postgres:14-alpine
    container_name: filmweeb-db
    environment:
      POSTGRES_DB: filmweeb
      POSTGRES_USER: filmweeb
      POSTGRES_PASSWORD: filmweeb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - filmweeb

  nginx-back:
    image: nginx:stable-alpine
    container_name: filmweeb-nginx-back
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - filmweeb
    ports:
      - 47450:80
    depends_on:
      - php


volumes:
  dbdata:

networks:
  filmweeb:

