version: "3.7"
services:
  app:
    build:
      args:
        user: jenkins
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: filmweeb-prod
    container_name: filmweeb-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - filmweeb

  db:
    image: 'postgres:14'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    container_name: filmweeb-db-prod
    restart: unless-stopped
    volumes:
      - 'filmweeb-prod-db:/var/lib/postgresql/data'
      - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - filmweeb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s


  nginx:
    image: nginx:alpine
    container_name: filmweeb-nginx-prod
    restart: unless-stopped
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - filmweeb

networks:
  filmweeb:
    driver: bridge
volumes:
  filmweeb-prod-db:
    driver: local
