apiVersion: batch/v1
kind: Job
metadata:
  name: filmweeb-migration
  namespace: filmweeb
spec:
  template:
    spec:
      containers:
      - name: migration
        image: harbor.skni.edu.pl/library/filmweeb-back:latest
        command: ['sh', '-c', 'php artisan migrate']
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 4

